-- Comprehensive Database Index Optimization
-- Targeting 75% performance improvement for common query patterns
-- Generated by Claude Code comprehensive optimization plan

-- ====================
-- CODE QUALITY INDEXES
-- ====================

-- Dashboard queries: Get latest reports by project
CREATE INDEX CONCURRENTLY IF NOT EXISTS "idx_code_quality_dashboard"
ON "code_quality_reports" ("projectId", "status", "createdAt" DESC);

-- Analytics queries: Score distribution analysis
CREATE INDEX CONCURRENTLY IF NOT EXISTS "idx_code_quality_analytics"
ON "code_quality_reports" ("status", "overallScore", "createdAt");

-- Performance monitoring: Processing time analysis
CREATE INDEX CONCURRENTLY IF NOT EXISTS "idx_code_quality_performance"
ON "code_quality_reports" ("status", "analysisTimeMs", "createdAt");

-- Progress tracking: Current stage and progress
CREATE INDEX CONCURRENTLY IF NOT EXISTS "idx_code_quality_progress"
ON "code_quality_reports" ("projectId", "status", "progress", "updatedAt");

-- Error analysis: Failed reports investigation
CREATE INDEX CONCURRENTLY IF NOT EXISTS "idx_code_quality_errors"
ON "code_quality_reports" ("status", "errorMessage", "createdAt")
WHERE "status" = 'FAILED';

-- Repository analysis: Same repo across projects
CREATE INDEX CONCURRENTLY IF NOT EXISTS "idx_code_quality_repository"
ON "code_quality_reports" ("repositoryUrl", "status", "createdAt");

-- ====================
-- INNOVATION INDEXES
-- ====================

-- Dashboard: Latest innovation reports
CREATE INDEX CONCURRENTLY IF NOT EXISTS "idx_innovation_dashboard"
ON "innovation_reports" ("projectId", "status", "createdAt" DESC);

-- Score analysis: Innovation metrics
CREATE INDEX CONCURRENTLY IF NOT EXISTS "idx_innovation_scores"
ON "innovation_reports" ("status", "score", "noveltyScore", "creativityScore");

-- Patent analysis: Patent potential tracking
CREATE INDEX CONCURRENTLY IF NOT EXISTS "idx_innovation_patents"
ON "innovation_reports" ("patentPotential", "patentabilityScore", "createdAt");

-- Archive management: Archived reports
CREATE INDEX CONCURRENTLY IF NOT EXISTS "idx_innovation_archive"
ON "innovation_reports" ("isArchived", "status", "updatedAt");

-- Processing time: Performance analysis
CREATE INDEX CONCURRENTLY IF NOT EXISTS "idx_innovation_processing"
ON "innovation_reports" ("status", "processingTime", "createdAt");

-- ====================
-- COHERENCE INDEXES
-- ====================

-- Dashboard: Coherence report status
CREATE INDEX CONCURRENTLY IF NOT EXISTS "idx_coherence_dashboard"
ON "coherence_reports" ("projectId", "status", "createdAt" DESC);

-- Track alignment analysis
CREATE INDEX CONCURRENTLY IF NOT EXISTS "idx_coherence_track"
ON "coherence_reports" ("status", "trackAlignment", "score");

-- README analysis: Quality tracking
CREATE INDEX CONCURRENTLY IF NOT EXISTS "idx_coherence_readme"
ON "coherence_reports" ("readmeExists", "readmeQuality", "status");

-- Progress monitoring: Analysis stages
CREATE INDEX CONCURRENTLY IF NOT EXISTS "idx_coherence_progress"
ON "coherence_reports" ("projectId", "status", "progress", "currentStage");

-- Performance tracking: Analysis duration
CREATE INDEX CONCURRENTLY IF NOT EXISTS "idx_coherence_performance"
ON "coherence_reports" ("status", "analysisTimeMs", "createdAt");

-- ====================
-- HEDERA INDEXES
-- ====================

-- Dashboard: Hedera analysis status
CREATE INDEX CONCURRENTLY IF NOT EXISTS "idx_hedera_dashboard"
ON "hedera_analysis_reports" ("projectId", "status", "createdAt" DESC);

-- Technology categorization
CREATE INDEX CONCURRENTLY IF NOT EXISTS "idx_hedera_technology"
ON "hedera_analysis_reports" ("technologyCategory", "confidence", "status");

-- Usage scoring: Hedera implementation quality
CREATE INDEX CONCURRENTLY IF NOT EXISTS "idx_hedera_usage"
ON "hedera_analysis_reports" ("status", "hederaUsageScore", "confidence");

-- Repository analysis: Same repo patterns
CREATE INDEX CONCURRENTLY IF NOT EXISTS "idx_hedera_repository"
ON "hedera_analysis_reports" ("repositoryUrl", "technologyCategory", "createdAt");

-- Progress tracking: Analysis stages
CREATE INDEX CONCURRENTLY IF NOT EXISTS "idx_hedera_progress"
ON "hedera_analysis_reports" ("projectId", "status", "progress", "currentStage");

-- Complexity analysis: Implementation depth
CREATE INDEX CONCURRENTLY IF NOT EXISTS "idx_hedera_complexity"
ON "hedera_analysis_reports" ("complexityLevel", "status", "confidence");

-- ====================
-- PROJECT INDEXES
-- ====================

-- Hackathon project listings (most common query)
CREATE INDEX CONCURRENTLY IF NOT EXISTS "idx_projects_hackathon"
ON "projects" ("hackathonId", "createdAt" DESC, "isEligible");

-- Project ownership and access control
CREATE INDEX CONCURRENTLY IF NOT EXISTS "idx_projects_access"
ON "projects" ("hackathonId", "teamId", "isEligible");

-- Repository URL lookups (for duplicate detection)
CREATE INDEX CONCURRENTLY IF NOT EXISTS "idx_projects_repository"
ON "projects" ("repositoryUrl", "hackathonId");

-- Track-based filtering
CREATE INDEX CONCURRENTLY IF NOT EXISTS "idx_projects_track"
ON "projects" ("trackId", "isEligible", "createdAt" DESC);

-- ====================
-- HACKATHON INDEXES
-- ====================

-- User hackathon access
CREATE INDEX CONCURRENTLY IF NOT EXISTS "idx_hackathons_creator"
ON "hackathons" ("createdById", "createdAt" DESC);

-- Active hackathons
CREATE INDEX CONCURRENTLY IF NOT EXISTS "idx_hackathons_active"
ON "hackathons" ("isActive", "endDate", "startDate");

-- ====================
-- TEAM INDEXES
-- ====================

-- Hackathon team listings
CREATE INDEX CONCURRENTLY IF NOT EXISTS "idx_teams_hackathon"
ON "teams" ("hackathonId", "createdAt" DESC);

-- Team member lookups
CREATE INDEX CONCURRENTLY IF NOT EXISTS "idx_team_members_lookup"
ON "team_members" ("teamId", "userId");

-- User team memberships
CREATE INDEX CONCURRENTLY IF NOT EXISTS "idx_team_members_user"
ON "team_members" ("userId", "teamId");

-- ====================
-- TRACK INDEXES
-- ====================

-- Hackathon tracks
CREATE INDEX CONCURRENTLY IF NOT EXISTS "idx_tracks_hackathon"
ON "tracks" ("hackathonId", "name");

-- ====================
-- ELIGIBILITY INDEXES
-- ====================

-- Project eligibility status
CREATE INDEX CONCURRENTLY IF NOT EXISTS "idx_eligibility_project"
ON "eligibility_reports" ("projectId", "status", "eligible");

-- Eligibility analytics
CREATE INDEX CONCURRENTLY IF NOT EXISTS "idx_eligibility_analytics"
ON "eligibility_reports" ("eligible", "overallScore", "createdAt");

-- ====================
-- NOTIFICATION INDEXES
-- ====================

-- User notifications (most frequent query)
CREATE INDEX CONCURRENTLY IF NOT EXISTS "idx_notifications_user"
ON "notifications" ("userId", "isRead", "createdAt" DESC);

-- Notification cleanup
CREATE INDEX CONCURRENTLY IF NOT EXISTS "idx_notifications_cleanup"
ON "notifications" ("createdAt", "isRead");

-- ====================
-- ACTIVITY LOG INDEXES
-- ====================

-- User activity tracking
CREATE INDEX CONCURRENTLY IF NOT EXISTS "idx_activity_user"
ON "activity_logs" ("userId", "createdAt" DESC);

-- Project activity
CREATE INDEX CONCURRENTLY IF NOT EXISTS "idx_activity_project"
ON "activity_logs" ("projectId", "action", "createdAt" DESC);

-- System activity monitoring
CREATE INDEX CONCURRENTLY IF NOT EXISTS "idx_activity_system"
ON "activity_logs" ("action", "createdAt" DESC);

-- ====================
-- COMPOSITE INDEXES FOR COMPLEX QUERIES
-- ====================

-- Complete project analysis status (dashboard overview)
CREATE INDEX CONCURRENTLY IF NOT EXISTS "idx_project_analysis_complete"
ON "projects" ("hackathonId", "isEligible", "createdAt" DESC, "repositoryUrl");

-- Multi-layer analysis correlation
CREATE INDEX CONCURRENTLY IF NOT EXISTS "idx_multi_analysis_correlation"
ON "code_quality_reports" ("projectId", "status", "overallScore", "createdAt");

-- Create similar indexes for other report types to enable cross-layer analysis
-- (Postgres will use these for JOIN operations)

-- Analysis performance tracking across all layers
CREATE INDEX CONCURRENTLY IF NOT EXISTS "idx_analysis_performance_tracking"
ON "code_quality_reports" ("createdAt", "analysisTimeMs", "status", "partialAnalysis");

-- ====================
-- MATERIALIZED VIEWS FOR ANALYTICS
-- ====================

-- Project analysis summary (most expensive query)
CREATE MATERIALIZED VIEW IF NOT EXISTS "mv_project_analysis_summary" AS
SELECT
    p."id" as "projectId",
    p."name" as "projectName",
    p."hackathonId",
    p."trackId",
    p."repositoryUrl",
    p."isEligible",
    p."createdAt",

    -- Code Quality metrics
    cq."overallScore" as "codeQualityScore",
    cq."status" as "codeQualityStatus",
    cq."analysisTimeMs" as "codeQualityTime",

    -- Innovation metrics
    inv."score" as "innovationScore",
    inv."status" as "innovationStatus",
    inv."processingTime" as "innovationTime",

    -- Coherence metrics
    coh."score" as "coherenceScore",
    coh."trackAlignment" as "trackAlignmentScore",
    coh."status" as "coherenceStatus",

    -- Hedera metrics
    hed."confidence" as "hederaConfidence",
    hed."hederaUsageScore" as "hederaScore",
    hed."technologyCategory" as "technologyCategory",
    hed."status" as "hederaStatus",

    -- Combined analysis status
    CASE
        WHEN cq."status" = 'COMPLETED' AND inv."status" = 'COMPLETED'
             AND coh."status" = 'COMPLETED' AND hed."status" = 'COMPLETED'
        THEN 'COMPLETE'
        WHEN cq."status" = 'FAILED' OR inv."status" = 'FAILED'
             OR coh."status" = 'FAILED' OR hed."status" = 'FAILED'
        THEN 'PARTIAL'
        ELSE 'IN_PROGRESS'
    END as "analysisStatus",

    -- Calculate unified score (using standard weights)
    CASE
        WHEN cq."overallScore" IS NOT NULL AND inv."score" IS NOT NULL
             AND coh."score" IS NOT NULL AND hed."confidence" IS NOT NULL
        THEN ROUND(
            (cq."overallScore" * 0.35) +
            (inv."score" * 0.25) +
            (coh."score" * 0.25) +
            (hed."confidence" * 0.15)
        )
        ELSE NULL
    END as "unifiedScore"

FROM "projects" p
LEFT JOIN LATERAL (
    SELECT * FROM "code_quality_reports"
    WHERE "projectId" = p."id"
    ORDER BY "createdAt" DESC
    LIMIT 1
) cq ON true
LEFT JOIN LATERAL (
    SELECT * FROM "innovation_reports"
    WHERE "projectId" = p."id"
    ORDER BY "createdAt" DESC
    LIMIT 1
) inv ON true
LEFT JOIN LATERAL (
    SELECT * FROM "coherence_reports"
    WHERE "projectId" = p."id"
    ORDER BY "createdAt" DESC
    LIMIT 1
) coh ON true
LEFT JOIN LATERAL (
    SELECT * FROM "hedera_analysis_reports"
    WHERE "projectId" = p."id"
    ORDER BY "createdAt" DESC
    LIMIT 1
) hed ON true;

-- Index for the materialized view
CREATE UNIQUE INDEX IF NOT EXISTS "idx_mv_project_analysis_summary_pk"
ON "mv_project_analysis_summary" ("projectId");

CREATE INDEX IF NOT EXISTS "idx_mv_project_analysis_summary_hackathon"
ON "mv_project_analysis_summary" ("hackathonId", "analysisStatus", "unifiedScore" DESC NULLS LAST);

CREATE INDEX IF NOT EXISTS "idx_mv_project_analysis_summary_scores"
ON "mv_project_analysis_summary" ("unifiedScore" DESC NULLS LAST, "codeQualityScore", "innovationScore");

-- ====================
-- REFRESH FUNCTION FOR MATERIALIZED VIEW
-- ====================

-- Function to refresh the materialized view
CREATE OR REPLACE FUNCTION refresh_project_analysis_summary()
RETURNS void AS $$
BEGIN
    REFRESH MATERIALIZED VIEW CONCURRENTLY "mv_project_analysis_summary";
END;
$$ LANGUAGE plpgsql;

-- ====================
-- PERFORMANCE MONITORING
-- ====================

-- View to monitor index usage
CREATE OR REPLACE VIEW "v_index_usage_stats" AS
SELECT
    schemaname,
    tablename,
    indexname,
    idx_tup_read,
    idx_tup_fetch,
    idx_scan
FROM pg_stat_user_indexes
ORDER BY idx_scan DESC;

-- View to monitor slow queries
CREATE OR REPLACE VIEW "v_slow_queries" AS
SELECT
    query,
    calls,
    total_time,
    mean_time,
    max_time,
    rows
FROM pg_stat_statements
WHERE mean_time > 1000  -- Queries taking more than 1 second on average
ORDER BY mean_time DESC;

-- ====================
-- MAINTENANCE TASKS
-- ====================

-- Analyze tables after index creation for optimal query planning
ANALYZE "projects";
ANALYZE "code_quality_reports";
ANALYZE "innovation_reports";
ANALYZE "coherence_reports";
ANALYZE "hedera_analysis_reports";
ANALYZE "teams";
ANALYZE "team_members";
ANALYZE "tracks";
ANALYZE "hackathons";
ANALYZE "eligibility_reports";
ANALYZE "notifications";
ANALYZE "activity_logs";