-- Basic Database Index Optimization (Non-Concurrent)
-- Targeting 75% performance improvement for common query patterns
-- Generated by Claude Code comprehensive optimization plan

-- ====================
-- CODE QUALITY INDEXES
-- ====================

-- Dashboard queries: Get latest reports by project
CREATE INDEX IF NOT EXISTS "idx_code_quality_dashboard"
ON "code_quality_reports" ("projectId", "status", "createdAt" DESC);

-- Analytics queries: Score distribution analysis
CREATE INDEX IF NOT EXISTS "idx_code_quality_analytics"
ON "code_quality_reports" ("status", "overallScore", "createdAt");

-- Performance monitoring: Processing time analysis
CREATE INDEX IF NOT EXISTS "idx_code_quality_performance"
ON "code_quality_reports" ("status", "analysisTimeMs", "createdAt");

-- Progress tracking: Current stage and progress
CREATE INDEX IF NOT EXISTS "idx_code_quality_progress"
ON "code_quality_reports" ("projectId", "status", "progress", "updatedAt");

-- Repository analysis: Same repo across projects
CREATE INDEX IF NOT EXISTS "idx_code_quality_repository"
ON "code_quality_reports" ("repositoryUrl", "status", "createdAt");

-- ====================
-- INNOVATION INDEXES
-- ====================

-- Dashboard: Latest innovation reports
CREATE INDEX IF NOT EXISTS "idx_innovation_dashboard"
ON "innovation_reports" ("projectId", "status", "createdAt" DESC);

-- Score analysis: Innovation metrics
CREATE INDEX IF NOT EXISTS "idx_innovation_scores"
ON "innovation_reports" ("status", "score", "noveltyScore", "creativityScore");

-- Patent analysis: Patent potential tracking
CREATE INDEX IF NOT EXISTS "idx_innovation_patents"
ON "innovation_reports" ("patentPotential", "patentabilityScore", "createdAt");

-- Archive management: Archived reports
CREATE INDEX IF NOT EXISTS "idx_innovation_archive"
ON "innovation_reports" ("isArchived", "status", "updatedAt");

-- Processing time: Performance analysis
CREATE INDEX IF NOT EXISTS "idx_innovation_processing"
ON "innovation_reports" ("status", "processingTime", "createdAt");

-- ====================
-- COHERENCE INDEXES
-- ====================

-- Dashboard: Coherence report status
CREATE INDEX IF NOT EXISTS "idx_coherence_dashboard"
ON "coherence_reports" ("projectId", "status", "createdAt" DESC);

-- Track alignment analysis
CREATE INDEX IF NOT EXISTS "idx_coherence_track"
ON "coherence_reports" ("status", "trackAlignment", "score");

-- README analysis: Quality tracking
CREATE INDEX IF NOT EXISTS "idx_coherence_readme"
ON "coherence_reports" ("readmeExists", "readmeQuality", "status");

-- Progress monitoring: Analysis stages
CREATE INDEX IF NOT EXISTS "idx_coherence_progress"
ON "coherence_reports" ("projectId", "status", "progress", "currentStage");

-- Performance tracking: Analysis duration
CREATE INDEX IF NOT EXISTS "idx_coherence_performance"
ON "coherence_reports" ("status", "analysisTimeMs", "createdAt");

-- ====================
-- HEDERA INDEXES
-- ====================

-- Dashboard: Hedera analysis status
CREATE INDEX IF NOT EXISTS "idx_hedera_dashboard"
ON "hedera_analysis_reports" ("projectId", "status", "createdAt" DESC);

-- Technology categorization
CREATE INDEX IF NOT EXISTS "idx_hedera_technology"
ON "hedera_analysis_reports" ("technologyCategory", "confidence", "status");

-- Usage scoring: Hedera implementation quality
CREATE INDEX IF NOT EXISTS "idx_hedera_usage"
ON "hedera_analysis_reports" ("status", "hederaUsageScore", "confidence");

-- Repository analysis: Same repo patterns
CREATE INDEX IF NOT EXISTS "idx_hedera_repository"
ON "hedera_analysis_reports" ("repositoryUrl", "technologyCategory", "createdAt");

-- Progress tracking: Analysis stages
CREATE INDEX IF NOT EXISTS "idx_hedera_progress"
ON "hedera_analysis_reports" ("projectId", "status", "progress", "currentStage");

-- Complexity analysis: Implementation depth
CREATE INDEX IF NOT EXISTS "idx_hedera_complexity"
ON "hedera_analysis_reports" ("complexityLevel", "status", "confidence");

-- ====================
-- PROJECT INDEXES
-- ====================

-- Hackathon project listings (most common query)
CREATE INDEX IF NOT EXISTS "idx_projects_hackathon"
ON "projects" ("hackathonId", "createdAt" DESC, "isEligible");

-- Project ownership and access control
CREATE INDEX IF NOT EXISTS "idx_projects_access"
ON "projects" ("hackathonId", "teamId", "isEligible");

-- Repository URL lookups (for duplicate detection)
CREATE INDEX IF NOT EXISTS "idx_projects_repository"
ON "projects" ("repositoryUrl", "hackathonId");

-- Track-based filtering
CREATE INDEX IF NOT EXISTS "idx_projects_track"
ON "projects" ("trackId", "isEligible", "createdAt" DESC);

-- ====================
-- HACKATHON INDEXES
-- ====================

-- User hackathon access
CREATE INDEX IF NOT EXISTS "idx_hackathons_creator"
ON "hackathons" ("createdById", "createdAt" DESC);

-- Active hackathons
CREATE INDEX IF NOT EXISTS "idx_hackathons_active"
ON "hackathons" ("isActive", "endDate", "startDate");

-- ====================
-- TEAM INDEXES
-- ====================

-- Hackathon team listings
CREATE INDEX IF NOT EXISTS "idx_teams_hackathon"
ON "teams" ("hackathonId", "createdAt" DESC);

-- Team member lookups
CREATE INDEX IF NOT EXISTS "idx_team_members_lookup"
ON "team_members" ("teamId", "userId");

-- User team memberships
CREATE INDEX IF NOT EXISTS "idx_team_members_user"
ON "team_members" ("userId", "teamId");

-- ====================
-- TRACK INDEXES
-- ====================

-- Hackathon tracks
CREATE INDEX IF NOT EXISTS "idx_tracks_hackathon"
ON "tracks" ("hackathonId", "name");

-- ====================
-- ELIGIBILITY INDEXES
-- ====================

-- Project eligibility status
CREATE INDEX IF NOT EXISTS "idx_eligibility_project"
ON "eligibility_reports" ("projectId", "status", "eligible");

-- Eligibility analytics
CREATE INDEX IF NOT EXISTS "idx_eligibility_analytics"
ON "eligibility_reports" ("eligible", "overallScore", "createdAt");

-- ====================
-- NOTIFICATION INDEXES
-- ====================

-- User notifications (most frequent query)
CREATE INDEX IF NOT EXISTS "idx_notifications_user"
ON "notifications" ("userId", "isRead", "createdAt" DESC);

-- Notification cleanup
CREATE INDEX IF NOT EXISTS "idx_notifications_cleanup"
ON "notifications" ("createdAt", "isRead");

-- ====================
-- ACTIVITY LOG INDEXES
-- ====================

-- User activity tracking
CREATE INDEX IF NOT EXISTS "idx_activity_user"
ON "activity_logs" ("userId", "createdAt" DESC);

-- Project activity
CREATE INDEX IF NOT EXISTS "idx_activity_project"
ON "activity_logs" ("projectId", "action", "createdAt" DESC);

-- System activity monitoring
CREATE INDEX IF NOT EXISTS "idx_activity_system"
ON "activity_logs" ("action", "createdAt" DESC);

-- ====================
-- COMPOSITE INDEXES FOR COMPLEX QUERIES
-- ====================

-- Complete project analysis status (dashboard overview)
CREATE INDEX IF NOT EXISTS "idx_project_analysis_complete"
ON "projects" ("hackathonId", "isEligible", "createdAt" DESC, "repositoryUrl");

-- ====================
-- PERFORMANCE MONITORING
-- ====================

-- Analyze tables after index creation for optimal query planning
ANALYZE "projects";
ANALYZE "code_quality_reports";
ANALYZE "innovation_reports";
ANALYZE "coherence_reports";
ANALYZE "hedera_analysis_reports";
ANALYZE "teams";
ANALYZE "team_members";
ANALYZE "tracks";
ANALYZE "hackathons";
ANALYZE "eligibility_reports";
ANALYZE "notifications";
ANALYZE "activity_logs";