-- Add score validation constraints (0-100 range) to all analysis layers
-- Generated by Claude Code for fairness improvements

-- Code Quality Report score constraints
ALTER TABLE "code_quality_reports" ADD CONSTRAINT "chk_code_quality_overall_score"
  CHECK ("overallScore" IS NULL OR ("overallScore" >= 0 AND "overallScore" <= 100));

ALTER TABLE "code_quality_reports" ADD CONSTRAINT "chk_code_quality_technical_score"
  CHECK ("technicalScore" IS NULL OR ("technicalScore" >= 0 AND "technicalScore" <= 100));

ALTER TABLE "code_quality_reports" ADD CONSTRAINT "chk_code_quality_security_score"
  CHECK ("securityScore" IS NULL OR ("securityScore" >= 0 AND "securityScore" <= 100));

ALTER TABLE "code_quality_reports" ADD CONSTRAINT "chk_code_quality_documentation_score"
  CHECK ("documentationScore" IS NULL OR ("documentationScore" >= 0 AND "documentationScore" <= 100));

ALTER TABLE "code_quality_reports" ADD CONSTRAINT "chk_code_quality_performance_score"
  CHECK ("performanceScore" IS NULL OR ("performanceScore" >= 0 AND "performanceScore" <= 100));

ALTER TABLE "code_quality_reports" ADD CONSTRAINT "chk_code_quality_richness_score"
  CHECK ("richnessScore" IS NULL OR ("richnessScore" >= 0 AND "richnessScore" <= 100));

-- Innovation Report score constraints
ALTER TABLE "innovation_reports" ADD CONSTRAINT "chk_innovation_score"
  CHECK ("score" >= 0 AND "score" <= 100);

ALTER TABLE "innovation_reports" ADD CONSTRAINT "chk_innovation_novelty_score"
  CHECK ("noveltyScore" >= 0 AND "noveltyScore" <= 100);

ALTER TABLE "innovation_reports" ADD CONSTRAINT "chk_innovation_creativity_score"
  CHECK ("creativityScore" >= 0 AND "creativityScore" <= 100);

ALTER TABLE "innovation_reports" ADD CONSTRAINT "chk_innovation_technical_innovation"
  CHECK ("technicalInnovation" >= 0 AND "technicalInnovation" <= 100);

ALTER TABLE "innovation_reports" ADD CONSTRAINT "chk_innovation_market_innovation"
  CHECK ("marketInnovation" >= 0 AND "marketInnovation" <= 100);

ALTER TABLE "innovation_reports" ADD CONSTRAINT "chk_innovation_implementation_innovation"
  CHECK ("implementationInnovation" >= 0 AND "implementationInnovation" <= 100);

ALTER TABLE "innovation_reports" ADD CONSTRAINT "chk_innovation_patentability_score"
  CHECK ("patentabilityScore" IS NULL OR ("patentabilityScore" >= 0 AND "patentabilityScore" <= 100));

-- Coherence Report score constraints
ALTER TABLE "coherence_reports" ADD CONSTRAINT "chk_coherence_score"
  CHECK ("score" >= 0 AND "score" <= 100);

ALTER TABLE "coherence_reports" ADD CONSTRAINT "chk_coherence_track_alignment"
  CHECK ("trackAlignment" >= 0 AND "trackAlignment" <= 100);

ALTER TABLE "coherence_reports" ADD CONSTRAINT "chk_coherence_readme_quality"
  CHECK ("readmeQuality" >= 0 AND "readmeQuality" <= 100);

-- Hedera Analysis Report score constraints
ALTER TABLE "hedera_analysis_reports" ADD CONSTRAINT "chk_hedera_confidence"
  CHECK ("confidence" >= 0 AND "confidence" <= 100);

ALTER TABLE "hedera_analysis_reports" ADD CONSTRAINT "chk_hedera_usage_score"
  CHECK ("hederaUsageScore" IS NULL OR ("hederaUsageScore" >= 0 AND "hederaUsageScore" <= 100));

-- Eligibility Report score constraints
ALTER TABLE "eligibility_reports" ADD CONSTRAINT "chk_eligibility_overall_score"
  CHECK ("overallScore" >= 0 AND "overallScore" <= 100);

-- Progress field constraints (0-100 percentage)
ALTER TABLE "code_quality_reports" ADD CONSTRAINT "chk_code_quality_progress"
  CHECK ("progress" >= 0 AND "progress" <= 100);

ALTER TABLE "hedera_analysis_reports" ADD CONSTRAINT "chk_hedera_progress"
  CHECK ("progress" >= 0 AND "progress" <= 100);

ALTER TABLE "coherence_reports" ADD CONSTRAINT "chk_coherence_progress"
  CHECK ("progress" >= 0 AND "progress" <= 100);