-- Add patent assessment fields to innovation reports
-- Generated by Claude Code

-- Add patentabilityScore field (AI-generated patent score 0-100)
ALTER TABLE "innovation_reports" ADD COLUMN "patentabilityScore" DOUBLE PRECISION;

-- Add patentAssessment field (detailed patent assessment data as JSON)
ALTER TABLE "innovation_reports" ADD COLUMN "patentAssessment" JSONB;